//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet
{
    /// <summary>
    ///     Lists all generated quantities with the same name as the quantity struct type,
    ///     such as Length, Mass, Force etc.
    ///     This is useful for populating options in the UI, such as creating a generic conversion
    ///     tool with inputValue, quantityName, fromUnit and toUnit selectors.
    /// </summary>
    public enum QuantityType
    {
// Missing XML comment for public type or member
#pragma warning disable CS1591
        Undefined = 0,
        AbsorbedDose,
        Acceleration,
        Activity,
        AmountOfSubstance,
        AmplitudeRatio,
        Angle,
        ApparentEnergy,
        ApparentPower,
        Area,
        AreaDensity,
        AreaMomentOfInertia,
        AreaVolumeRation,
        BaudRate,
        BitRate,
        BrakeSpecificFuelConsumption,
        Capacitance,
        CatalyticActivity,
        CatalyticVolumeActivity,
        CoefficientOfThermalExpansion,
        Density,
        Diffusivity,
        DoseRate,
        Duration,
        DynamicViscosity,
        ElectricAdmittance,
        ElectricCharge,
        ElectricChargeDensity,
        ElectricConductance,
        ElectricConductivity,
        ElectricCurrent,
        ElectricCurrentDensity,
        ElectricCurrentGradient,
        ElectricField,
        ElectricInductance,
        ElectricPotential,
        ElectricPotentialAc,
        ElectricPotentialChangeRate,
        ElectricPotentialDc,
        ElectricResistance,
        ElectricResistivity,
        ElectricSurfaceChargeDensity,
        Energy,
        EnergyDensity,
        Entropy,
        Force,
        ForceChangeRate,
        ForcePerLength,
        Frequency,
        FuelEfficiency,
        HeatCapacity,
        HeatFlux,
        HeatTransferCoefficient,
        Illuminance,
        Information,
        IonDose,
        Irradiance,
        Irradiation,
        KinematicViscosity,
        LapseRate,
        Length,
        Level,
        LinearDensity,
        LinearPowerDensity,
        Luminance,
        Luminosity,
        LuminousEfficacy,
        LuminousFlux,
        LuminousIntensity,
        MagneticField,
        MagneticFlux,
        Magnetization,
        Mass,
        MassConcentration,
        MassFlow,
        MassFlux,
        MassFraction,
        MassMomentOfInertia,
        MolarEnergy,
        MolarEntropy,
        Molarity,
        MolarMass,
        Permeability,
        Permeance,
        Permittivity,
        Power,
        PowerDensity,
        PowerRatio,
        Pressure,
        PressureChangeRate,
        PressureGradient,
        Radiance,
        RadiantIntensity,
        Ratio,
        RatioChangeRate,
        ReactiveEnergy,
        ReactivePower,
        RotationalAcceleration,
        RotationalSpeed,
        RotationalStiffness,
        RotationalStiffnessPerLength,
        SolidAngle,
        SpaceVelocity,
        SpecificArea,
        SpecificDischarge,
        SpecificEnergy,
        SpecificEntropy,
        SpecificHeatEnergy,
        SpecificLength,
        SpecificVolume,
        SpecificWeight,
        Speed,
        Temperature,
        TemperatureChangeRate,
        TemperatureCoefficient,
        TemperatureDelta,
        ThermalLengthExpansion,
        ThermalConductance,
        ThermalConductivity,
        ThermalInsulance,
        ThermalResistance,
        Torque,
        TorquePerLength,
        VitaminA,
        Volume,
        VolumeConcentration,
        VolumeFlow,
        VolumePerLength,
// Missing XML comment for public type or member
#pragma warning restore CS1591
    }
}
