//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of AbsorbedDose.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class AbsorbedDoseTestsBase
    {
        protected abstract double GraysInOneGray { get; }
        protected abstract double SievertsInOneGray { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double GraysTolerance { get { return 1e-5; } }
        protected virtual double SievertsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new AbsorbedDose((double)0.0, AbsorbedDoseUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new AbsorbedDose();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(AbsorbedDoseUnit.Gray, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new AbsorbedDose(double.PositiveInfinity, AbsorbedDoseUnit.Gray));
            Assert.Throws<ArgumentException>(() => new AbsorbedDose(double.NegativeInfinity, AbsorbedDoseUnit.Gray));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new AbsorbedDose(double.NaN, AbsorbedDoseUnit.Gray));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new AbsorbedDose(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void AbsorbedDose_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new AbsorbedDose(1, AbsorbedDoseUnit.Gray);

            QuantityInfo<AbsorbedDoseUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(AbsorbedDose.Zero, quantityInfo.Zero);
            Assert.Equal("AbsorbedDose", quantityInfo.Name);
            Assert.Equal(QuantityType.AbsorbedDose, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<AbsorbedDoseUnit>().Except(new[] {AbsorbedDoseUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void GrayToAbsorbedDoseUnits()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            AssertEx.EqualTolerance(GraysInOneGray, gray.Grays, GraysTolerance);
            AssertEx.EqualTolerance(SievertsInOneGray, gray.Sieverts, SievertsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = AbsorbedDose.From(1, AbsorbedDoseUnit.Gray);
            AssertEx.EqualTolerance(1, quantity00.Grays, GraysTolerance);
            Assert.Equal(AbsorbedDoseUnit.Gray, quantity00.Unit);

            var quantity01 = AbsorbedDose.From(1, AbsorbedDoseUnit.Sievert);
            AssertEx.EqualTolerance(1, quantity01.Sieverts, SievertsTolerance);
            Assert.Equal(AbsorbedDoseUnit.Sievert, quantity01.Unit);

        }

        [Fact]
        public void FromGrays_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => AbsorbedDose.FromGrays(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => AbsorbedDose.FromGrays(double.NegativeInfinity));
        }

        [Fact]
        public void FromGrays_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => AbsorbedDose.FromGrays(double.NaN));
        }

        [Fact]
        public void As()
        {
            var gray = AbsorbedDose.FromGrays(1);
            AssertEx.EqualTolerance(GraysInOneGray, gray.As(AbsorbedDoseUnit.Gray), GraysTolerance);
            AssertEx.EqualTolerance(SievertsInOneGray, gray.As(AbsorbedDoseUnit.Sievert), SievertsTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var gray = AbsorbedDose.FromGrays(1);

            var grayQuantity = gray.ToUnit(AbsorbedDoseUnit.Gray);
            AssertEx.EqualTolerance(GraysInOneGray, (double)grayQuantity.Value, GraysTolerance);
            Assert.Equal(AbsorbedDoseUnit.Gray, grayQuantity.Unit);

            var sievertQuantity = gray.ToUnit(AbsorbedDoseUnit.Sievert);
            AssertEx.EqualTolerance(SievertsInOneGray, (double)sievertQuantity.Value, SievertsTolerance);
            Assert.Equal(AbsorbedDoseUnit.Sievert, sievertQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            AssertEx.EqualTolerance(1, AbsorbedDose.FromGrays(gray.Grays).Grays, GraysTolerance);
            AssertEx.EqualTolerance(1, AbsorbedDose.FromSieverts(gray.Sieverts).Grays, SievertsTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            AbsorbedDose v = AbsorbedDose.FromGrays(1);
            AssertEx.EqualTolerance(-1, -v.Grays, GraysTolerance);
            AssertEx.EqualTolerance(2, (AbsorbedDose.FromGrays(3)-v).Grays, GraysTolerance);
            AssertEx.EqualTolerance(2, (v + v).Grays, GraysTolerance);
            AssertEx.EqualTolerance(10, (v*10).Grays, GraysTolerance);
            AssertEx.EqualTolerance(10, (10*v).Grays, GraysTolerance);
            AssertEx.EqualTolerance(2, (AbsorbedDose.FromGrays(10)/5).Grays, GraysTolerance);
            AssertEx.EqualTolerance(2, AbsorbedDose.FromGrays(10)/AbsorbedDose.FromGrays(5), GraysTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            AbsorbedDose oneGray = AbsorbedDose.FromGrays(1);
            AbsorbedDose twoGrays = AbsorbedDose.FromGrays(2);

            Assert.True(oneGray < twoGrays);
            Assert.True(oneGray <= twoGrays);
            Assert.True(twoGrays > oneGray);
            Assert.True(twoGrays >= oneGray);

            Assert.False(oneGray > twoGrays);
            Assert.False(oneGray >= twoGrays);
            Assert.False(twoGrays < oneGray);
            Assert.False(twoGrays <= oneGray);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            Assert.Equal(0, gray.CompareTo(gray));
            Assert.True(gray.CompareTo(AbsorbedDose.Zero) > 0);
            Assert.True(AbsorbedDose.Zero.CompareTo(gray) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            Assert.Throws<ArgumentException>(() => gray.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            Assert.Throws<ArgumentNullException>(() => gray.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = AbsorbedDose.FromGrays(1);
            var b = AbsorbedDose.FromGrays(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = AbsorbedDose.FromGrays(1);
            var b = AbsorbedDose.FromGrays(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = AbsorbedDose.FromGrays(1);
            object b = AbsorbedDose.FromGrays(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = AbsorbedDose.FromGrays(1);
            Assert.True(v.Equals(AbsorbedDose.FromGrays(1), GraysTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(AbsorbedDose.Zero, GraysTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = AbsorbedDose.FromGrays(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(AbsorbedDose.FromGrays(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            Assert.False(gray.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            AbsorbedDose gray = AbsorbedDose.FromGrays(1);
            Assert.False(gray.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(AbsorbedDoseUnit.Undefined, AbsorbedDose.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(AbsorbedDoseUnit)).Cast<AbsorbedDoseUnit>();
            foreach(var unit in units)
            {
                if(unit == AbsorbedDoseUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(AbsorbedDose.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 Gy", new AbsorbedDose(1, AbsorbedDoseUnit.Gray).ToString());
                Assert.Equal("1 Sv", new AbsorbedDose(1, AbsorbedDoseUnit.Sievert).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 Gy", new AbsorbedDose(1, AbsorbedDoseUnit.Gray).ToString(swedishCulture));
            Assert.Equal("1 Sv", new AbsorbedDose(1, AbsorbedDoseUnit.Sievert).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s1"));
                Assert.Equal("0.12 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s2"));
                Assert.Equal("0.123 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s3"));
                Assert.Equal("0.1235 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s1", culture));
            Assert.Equal("0.12 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s2", culture));
            Assert.Equal("0.123 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s3", culture));
            Assert.Equal("0.1235 Gy", new AbsorbedDose(0.123456, AbsorbedDoseUnit.Gray).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(AbsorbedDose)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(AbsorbedDoseUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(QuantityType.AbsorbedDose, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(AbsorbedDose.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = AbsorbedDose.FromGrays(1.0);
            Assert.Equal(new {AbsorbedDose.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = AbsorbedDose.FromGrays(value);
            Assert.Equal(AbsorbedDose.FromGrays(-value), -quantity);
        }

    }
}
