//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of AreaVolumeRation.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class AreaVolumeRationTestsBase
    {
        protected abstract double SquareMeterPerLitersInOneSquareMeterPerLiter { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double SquareMeterPerLitersTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new AreaVolumeRation((double)0.0, AreaVolumeRationUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new AreaVolumeRation();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(AreaVolumeRationUnit.SquareMeterPerLiter, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new AreaVolumeRation(double.PositiveInfinity, AreaVolumeRationUnit.SquareMeterPerLiter));
            Assert.Throws<ArgumentException>(() => new AreaVolumeRation(double.NegativeInfinity, AreaVolumeRationUnit.SquareMeterPerLiter));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new AreaVolumeRation(double.NaN, AreaVolumeRationUnit.SquareMeterPerLiter));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new AreaVolumeRation(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void AreaVolumeRation_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new AreaVolumeRation(1, AreaVolumeRationUnit.SquareMeterPerLiter);

            QuantityInfo<AreaVolumeRationUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(AreaVolumeRation.Zero, quantityInfo.Zero);
            Assert.Equal("AreaVolumeRation", quantityInfo.Name);
            Assert.Equal(QuantityType.AreaVolumeRation, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<AreaVolumeRationUnit>().Except(new[] {AreaVolumeRationUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void SquareMeterPerLiterToAreaVolumeRationUnits()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            AssertEx.EqualTolerance(SquareMeterPerLitersInOneSquareMeterPerLiter, squaremeterperliter.SquareMeterPerLiters, SquareMeterPerLitersTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = AreaVolumeRation.From(1, AreaVolumeRationUnit.SquareMeterPerLiter);
            AssertEx.EqualTolerance(1, quantity00.SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            Assert.Equal(AreaVolumeRationUnit.SquareMeterPerLiter, quantity00.Unit);

        }

        [Fact]
        public void FromSquareMeterPerLiters_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => AreaVolumeRation.FromSquareMeterPerLiters(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => AreaVolumeRation.FromSquareMeterPerLiters(double.NegativeInfinity));
        }

        [Fact]
        public void FromSquareMeterPerLiters_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => AreaVolumeRation.FromSquareMeterPerLiters(double.NaN));
        }

        [Fact]
        public void As()
        {
            var squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            AssertEx.EqualTolerance(SquareMeterPerLitersInOneSquareMeterPerLiter, squaremeterperliter.As(AreaVolumeRationUnit.SquareMeterPerLiter), SquareMeterPerLitersTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);

            var squaremeterperliterQuantity = squaremeterperliter.ToUnit(AreaVolumeRationUnit.SquareMeterPerLiter);
            AssertEx.EqualTolerance(SquareMeterPerLitersInOneSquareMeterPerLiter, (double)squaremeterperliterQuantity.Value, SquareMeterPerLitersTolerance);
            Assert.Equal(AreaVolumeRationUnit.SquareMeterPerLiter, squaremeterperliterQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            AssertEx.EqualTolerance(1, AreaVolumeRation.FromSquareMeterPerLiters(squaremeterperliter.SquareMeterPerLiters).SquareMeterPerLiters, SquareMeterPerLitersTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            AreaVolumeRation v = AreaVolumeRation.FromSquareMeterPerLiters(1);
            AssertEx.EqualTolerance(-1, -v.SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            AssertEx.EqualTolerance(2, (AreaVolumeRation.FromSquareMeterPerLiters(3)-v).SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            AssertEx.EqualTolerance(2, (v + v).SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            AssertEx.EqualTolerance(10, (v*10).SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            AssertEx.EqualTolerance(10, (10*v).SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            AssertEx.EqualTolerance(2, (AreaVolumeRation.FromSquareMeterPerLiters(10)/5).SquareMeterPerLiters, SquareMeterPerLitersTolerance);
            AssertEx.EqualTolerance(2, AreaVolumeRation.FromSquareMeterPerLiters(10)/AreaVolumeRation.FromSquareMeterPerLiters(5), SquareMeterPerLitersTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            AreaVolumeRation oneSquareMeterPerLiter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            AreaVolumeRation twoSquareMeterPerLiters = AreaVolumeRation.FromSquareMeterPerLiters(2);

            Assert.True(oneSquareMeterPerLiter < twoSquareMeterPerLiters);
            Assert.True(oneSquareMeterPerLiter <= twoSquareMeterPerLiters);
            Assert.True(twoSquareMeterPerLiters > oneSquareMeterPerLiter);
            Assert.True(twoSquareMeterPerLiters >= oneSquareMeterPerLiter);

            Assert.False(oneSquareMeterPerLiter > twoSquareMeterPerLiters);
            Assert.False(oneSquareMeterPerLiter >= twoSquareMeterPerLiters);
            Assert.False(twoSquareMeterPerLiters < oneSquareMeterPerLiter);
            Assert.False(twoSquareMeterPerLiters <= oneSquareMeterPerLiter);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.Equal(0, squaremeterperliter.CompareTo(squaremeterperliter));
            Assert.True(squaremeterperliter.CompareTo(AreaVolumeRation.Zero) > 0);
            Assert.True(AreaVolumeRation.Zero.CompareTo(squaremeterperliter) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.Throws<ArgumentException>(() => squaremeterperliter.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.Throws<ArgumentNullException>(() => squaremeterperliter.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = AreaVolumeRation.FromSquareMeterPerLiters(1);
            var b = AreaVolumeRation.FromSquareMeterPerLiters(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = AreaVolumeRation.FromSquareMeterPerLiters(1);
            var b = AreaVolumeRation.FromSquareMeterPerLiters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = AreaVolumeRation.FromSquareMeterPerLiters(1);
            object b = AreaVolumeRation.FromSquareMeterPerLiters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.True(v.Equals(AreaVolumeRation.FromSquareMeterPerLiters(1), SquareMeterPerLitersTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(AreaVolumeRation.Zero, SquareMeterPerLitersTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(AreaVolumeRation.FromSquareMeterPerLiters(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.False(squaremeterperliter.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            AreaVolumeRation squaremeterperliter = AreaVolumeRation.FromSquareMeterPerLiters(1);
            Assert.False(squaremeterperliter.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(AreaVolumeRationUnit.Undefined, AreaVolumeRation.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(AreaVolumeRationUnit)).Cast<AreaVolumeRationUnit>();
            foreach(var unit in units)
            {
                if(unit == AreaVolumeRationUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(AreaVolumeRation.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 m²/l", new AreaVolumeRation(1, AreaVolumeRationUnit.SquareMeterPerLiter).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 m²/l", new AreaVolumeRation(1, AreaVolumeRationUnit.SquareMeterPerLiter).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s1"));
                Assert.Equal("0.12 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s2"));
                Assert.Equal("0.123 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s3"));
                Assert.Equal("0.1235 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s1", culture));
            Assert.Equal("0.12 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s2", culture));
            Assert.Equal("0.123 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s3", culture));
            Assert.Equal("0.1235 m²/l", new AreaVolumeRation(0.123456, AreaVolumeRationUnit.SquareMeterPerLiter).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(AreaVolumeRation)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(AreaVolumeRationUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(QuantityType.AreaVolumeRation, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(AreaVolumeRation.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(1.0);
            Assert.Equal(new {AreaVolumeRation.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = AreaVolumeRation.FromSquareMeterPerLiters(value);
            Assert.Equal(AreaVolumeRation.FromSquareMeterPerLiters(-value), -quantity);
        }

    }
}
