//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of Luminance.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class LuminanceTestsBase
    {
        protected abstract double CandelaPerSquareMetersInOneCandelaPerSquareMeter { get; }
        protected abstract double FootLambertsInOneCandelaPerSquareMeter { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double CandelaPerSquareMetersTolerance { get { return 1e-5; } }
        protected virtual double FootLambertsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Luminance((double)0.0, LuminanceUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new Luminance();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(LuminanceUnit.CandelaPerSquareMeter, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Luminance(double.PositiveInfinity, LuminanceUnit.CandelaPerSquareMeter));
            Assert.Throws<ArgumentException>(() => new Luminance(double.NegativeInfinity, LuminanceUnit.CandelaPerSquareMeter));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Luminance(double.NaN, LuminanceUnit.CandelaPerSquareMeter));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new Luminance(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void Luminance_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new Luminance(1, LuminanceUnit.CandelaPerSquareMeter);

            QuantityInfo<LuminanceUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(Luminance.Zero, quantityInfo.Zero);
            Assert.Equal("Luminance", quantityInfo.Name);
            Assert.Equal(QuantityType.Luminance, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<LuminanceUnit>().Except(new[] {LuminanceUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void CandelaPerSquareMeterToLuminanceUnits()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            AssertEx.EqualTolerance(CandelaPerSquareMetersInOneCandelaPerSquareMeter, candelapersquaremeter.CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(FootLambertsInOneCandelaPerSquareMeter, candelapersquaremeter.FootLamberts, FootLambertsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = Luminance.From(1, LuminanceUnit.CandelaPerSquareMeter);
            AssertEx.EqualTolerance(1, quantity00.CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            Assert.Equal(LuminanceUnit.CandelaPerSquareMeter, quantity00.Unit);

            var quantity01 = Luminance.From(1, LuminanceUnit.FootLambert);
            AssertEx.EqualTolerance(1, quantity01.FootLamberts, FootLambertsTolerance);
            Assert.Equal(LuminanceUnit.FootLambert, quantity01.Unit);

        }

        [Fact]
        public void FromCandelaPerSquareMeters_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => Luminance.FromCandelaPerSquareMeters(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => Luminance.FromCandelaPerSquareMeters(double.NegativeInfinity));
        }

        [Fact]
        public void FromCandelaPerSquareMeters_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => Luminance.FromCandelaPerSquareMeters(double.NaN));
        }

        [Fact]
        public void As()
        {
            var candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            AssertEx.EqualTolerance(CandelaPerSquareMetersInOneCandelaPerSquareMeter, candelapersquaremeter.As(LuminanceUnit.CandelaPerSquareMeter), CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(FootLambertsInOneCandelaPerSquareMeter, candelapersquaremeter.As(LuminanceUnit.FootLambert), FootLambertsTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);

            var candelapersquaremeterQuantity = candelapersquaremeter.ToUnit(LuminanceUnit.CandelaPerSquareMeter);
            AssertEx.EqualTolerance(CandelaPerSquareMetersInOneCandelaPerSquareMeter, (double)candelapersquaremeterQuantity.Value, CandelaPerSquareMetersTolerance);
            Assert.Equal(LuminanceUnit.CandelaPerSquareMeter, candelapersquaremeterQuantity.Unit);

            var footlambertQuantity = candelapersquaremeter.ToUnit(LuminanceUnit.FootLambert);
            AssertEx.EqualTolerance(FootLambertsInOneCandelaPerSquareMeter, (double)footlambertQuantity.Value, FootLambertsTolerance);
            Assert.Equal(LuminanceUnit.FootLambert, footlambertQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            AssertEx.EqualTolerance(1, Luminance.FromCandelaPerSquareMeters(candelapersquaremeter.CandelaPerSquareMeters).CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(1, Luminance.FromFootLamberts(candelapersquaremeter.FootLamberts).CandelaPerSquareMeters, FootLambertsTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            Luminance v = Luminance.FromCandelaPerSquareMeters(1);
            AssertEx.EqualTolerance(-1, -v.CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(2, (Luminance.FromCandelaPerSquareMeters(3)-v).CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(2, (v + v).CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(10, (v*10).CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(10, (10*v).CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(2, (Luminance.FromCandelaPerSquareMeters(10)/5).CandelaPerSquareMeters, CandelaPerSquareMetersTolerance);
            AssertEx.EqualTolerance(2, Luminance.FromCandelaPerSquareMeters(10)/Luminance.FromCandelaPerSquareMeters(5), CandelaPerSquareMetersTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            Luminance oneCandelaPerSquareMeter = Luminance.FromCandelaPerSquareMeters(1);
            Luminance twoCandelaPerSquareMeters = Luminance.FromCandelaPerSquareMeters(2);

            Assert.True(oneCandelaPerSquareMeter < twoCandelaPerSquareMeters);
            Assert.True(oneCandelaPerSquareMeter <= twoCandelaPerSquareMeters);
            Assert.True(twoCandelaPerSquareMeters > oneCandelaPerSquareMeter);
            Assert.True(twoCandelaPerSquareMeters >= oneCandelaPerSquareMeter);

            Assert.False(oneCandelaPerSquareMeter > twoCandelaPerSquareMeters);
            Assert.False(oneCandelaPerSquareMeter >= twoCandelaPerSquareMeters);
            Assert.False(twoCandelaPerSquareMeters < oneCandelaPerSquareMeter);
            Assert.False(twoCandelaPerSquareMeters <= oneCandelaPerSquareMeter);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            Assert.Equal(0, candelapersquaremeter.CompareTo(candelapersquaremeter));
            Assert.True(candelapersquaremeter.CompareTo(Luminance.Zero) > 0);
            Assert.True(Luminance.Zero.CompareTo(candelapersquaremeter) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            Assert.Throws<ArgumentException>(() => candelapersquaremeter.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            Assert.Throws<ArgumentNullException>(() => candelapersquaremeter.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = Luminance.FromCandelaPerSquareMeters(1);
            var b = Luminance.FromCandelaPerSquareMeters(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = Luminance.FromCandelaPerSquareMeters(1);
            var b = Luminance.FromCandelaPerSquareMeters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = Luminance.FromCandelaPerSquareMeters(1);
            object b = Luminance.FromCandelaPerSquareMeters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = Luminance.FromCandelaPerSquareMeters(1);
            Assert.True(v.Equals(Luminance.FromCandelaPerSquareMeters(1), CandelaPerSquareMetersTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(Luminance.Zero, CandelaPerSquareMetersTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = Luminance.FromCandelaPerSquareMeters(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(Luminance.FromCandelaPerSquareMeters(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            Assert.False(candelapersquaremeter.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            Luminance candelapersquaremeter = Luminance.FromCandelaPerSquareMeters(1);
            Assert.False(candelapersquaremeter.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(LuminanceUnit.Undefined, Luminance.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(LuminanceUnit)).Cast<LuminanceUnit>();
            foreach(var unit in units)
            {
                if(unit == LuminanceUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(Luminance.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 cd/m²", new Luminance(1, LuminanceUnit.CandelaPerSquareMeter).ToString());
                Assert.Equal("1 ftL", new Luminance(1, LuminanceUnit.FootLambert).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 cd/m²", new Luminance(1, LuminanceUnit.CandelaPerSquareMeter).ToString(swedishCulture));
            Assert.Equal("1 ftL", new Luminance(1, LuminanceUnit.FootLambert).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s1"));
                Assert.Equal("0.12 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s2"));
                Assert.Equal("0.123 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s3"));
                Assert.Equal("0.1235 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s1", culture));
            Assert.Equal("0.12 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s2", culture));
            Assert.Equal("0.123 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s3", culture));
            Assert.Equal("0.1235 cd/m²", new Luminance(0.123456, LuminanceUnit.CandelaPerSquareMeter).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(Luminance)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(LuminanceUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(QuantityType.Luminance, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(Luminance.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(1.0);
            Assert.Equal(new {Luminance.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = Luminance.FromCandelaPerSquareMeters(value);
            Assert.Equal(Luminance.FromCandelaPerSquareMeters(-value), -quantity);
        }

    }
}
