//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of LuminousEfficacy.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class LuminousEfficacyTestsBase
    {
        protected abstract double LumenPerWattsInOneLumenPerWatt { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double LumenPerWattsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new LuminousEfficacy((double)0.0, LuminousEfficacyUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new LuminousEfficacy();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(LuminousEfficacyUnit.LumenPerWatt, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new LuminousEfficacy(double.PositiveInfinity, LuminousEfficacyUnit.LumenPerWatt));
            Assert.Throws<ArgumentException>(() => new LuminousEfficacy(double.NegativeInfinity, LuminousEfficacyUnit.LumenPerWatt));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new LuminousEfficacy(double.NaN, LuminousEfficacyUnit.LumenPerWatt));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new LuminousEfficacy(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void LuminousEfficacy_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new LuminousEfficacy(1, LuminousEfficacyUnit.LumenPerWatt);

            QuantityInfo<LuminousEfficacyUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(LuminousEfficacy.Zero, quantityInfo.Zero);
            Assert.Equal("LuminousEfficacy", quantityInfo.Name);
            Assert.Equal(QuantityType.LuminousEfficacy, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<LuminousEfficacyUnit>().Except(new[] {LuminousEfficacyUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void LumenPerWattToLuminousEfficacyUnits()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            AssertEx.EqualTolerance(LumenPerWattsInOneLumenPerWatt, lumenperwatt.LumenPerWatts, LumenPerWattsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = LuminousEfficacy.From(1, LuminousEfficacyUnit.LumenPerWatt);
            AssertEx.EqualTolerance(1, quantity00.LumenPerWatts, LumenPerWattsTolerance);
            Assert.Equal(LuminousEfficacyUnit.LumenPerWatt, quantity00.Unit);

        }

        [Fact]
        public void FromLumenPerWatts_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => LuminousEfficacy.FromLumenPerWatts(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => LuminousEfficacy.FromLumenPerWatts(double.NegativeInfinity));
        }

        [Fact]
        public void FromLumenPerWatts_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => LuminousEfficacy.FromLumenPerWatts(double.NaN));
        }

        [Fact]
        public void As()
        {
            var lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            AssertEx.EqualTolerance(LumenPerWattsInOneLumenPerWatt, lumenperwatt.As(LuminousEfficacyUnit.LumenPerWatt), LumenPerWattsTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);

            var lumenperwattQuantity = lumenperwatt.ToUnit(LuminousEfficacyUnit.LumenPerWatt);
            AssertEx.EqualTolerance(LumenPerWattsInOneLumenPerWatt, (double)lumenperwattQuantity.Value, LumenPerWattsTolerance);
            Assert.Equal(LuminousEfficacyUnit.LumenPerWatt, lumenperwattQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            AssertEx.EqualTolerance(1, LuminousEfficacy.FromLumenPerWatts(lumenperwatt.LumenPerWatts).LumenPerWatts, LumenPerWattsTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            LuminousEfficacy v = LuminousEfficacy.FromLumenPerWatts(1);
            AssertEx.EqualTolerance(-1, -v.LumenPerWatts, LumenPerWattsTolerance);
            AssertEx.EqualTolerance(2, (LuminousEfficacy.FromLumenPerWatts(3)-v).LumenPerWatts, LumenPerWattsTolerance);
            AssertEx.EqualTolerance(2, (v + v).LumenPerWatts, LumenPerWattsTolerance);
            AssertEx.EqualTolerance(10, (v*10).LumenPerWatts, LumenPerWattsTolerance);
            AssertEx.EqualTolerance(10, (10*v).LumenPerWatts, LumenPerWattsTolerance);
            AssertEx.EqualTolerance(2, (LuminousEfficacy.FromLumenPerWatts(10)/5).LumenPerWatts, LumenPerWattsTolerance);
            AssertEx.EqualTolerance(2, LuminousEfficacy.FromLumenPerWatts(10)/LuminousEfficacy.FromLumenPerWatts(5), LumenPerWattsTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            LuminousEfficacy oneLumenPerWatt = LuminousEfficacy.FromLumenPerWatts(1);
            LuminousEfficacy twoLumenPerWatts = LuminousEfficacy.FromLumenPerWatts(2);

            Assert.True(oneLumenPerWatt < twoLumenPerWatts);
            Assert.True(oneLumenPerWatt <= twoLumenPerWatts);
            Assert.True(twoLumenPerWatts > oneLumenPerWatt);
            Assert.True(twoLumenPerWatts >= oneLumenPerWatt);

            Assert.False(oneLumenPerWatt > twoLumenPerWatts);
            Assert.False(oneLumenPerWatt >= twoLumenPerWatts);
            Assert.False(twoLumenPerWatts < oneLumenPerWatt);
            Assert.False(twoLumenPerWatts <= oneLumenPerWatt);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.Equal(0, lumenperwatt.CompareTo(lumenperwatt));
            Assert.True(lumenperwatt.CompareTo(LuminousEfficacy.Zero) > 0);
            Assert.True(LuminousEfficacy.Zero.CompareTo(lumenperwatt) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.Throws<ArgumentException>(() => lumenperwatt.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.Throws<ArgumentNullException>(() => lumenperwatt.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = LuminousEfficacy.FromLumenPerWatts(1);
            var b = LuminousEfficacy.FromLumenPerWatts(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = LuminousEfficacy.FromLumenPerWatts(1);
            var b = LuminousEfficacy.FromLumenPerWatts(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = LuminousEfficacy.FromLumenPerWatts(1);
            object b = LuminousEfficacy.FromLumenPerWatts(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.True(v.Equals(LuminousEfficacy.FromLumenPerWatts(1), LumenPerWattsTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(LuminousEfficacy.Zero, LumenPerWattsTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(LuminousEfficacy.FromLumenPerWatts(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.False(lumenperwatt.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            LuminousEfficacy lumenperwatt = LuminousEfficacy.FromLumenPerWatts(1);
            Assert.False(lumenperwatt.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(LuminousEfficacyUnit.Undefined, LuminousEfficacy.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(LuminousEfficacyUnit)).Cast<LuminousEfficacyUnit>();
            foreach(var unit in units)
            {
                if(unit == LuminousEfficacyUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(LuminousEfficacy.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 lm/W", new LuminousEfficacy(1, LuminousEfficacyUnit.LumenPerWatt).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 lm/W", new LuminousEfficacy(1, LuminousEfficacyUnit.LumenPerWatt).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s1"));
                Assert.Equal("0.12 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s2"));
                Assert.Equal("0.123 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s3"));
                Assert.Equal("0.1235 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s1", culture));
            Assert.Equal("0.12 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s2", culture));
            Assert.Equal("0.123 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s3", culture));
            Assert.Equal("0.1235 lm/W", new LuminousEfficacy(0.123456, LuminousEfficacyUnit.LumenPerWatt).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(LuminousEfficacy)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(LuminousEfficacyUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(QuantityType.LuminousEfficacy, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(LuminousEfficacy.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(1.0);
            Assert.Equal(new {LuminousEfficacy.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = LuminousEfficacy.FromLumenPerWatts(value);
            Assert.Equal(LuminousEfficacy.FromLumenPerWatts(-value), -quantity);
        }

    }
}
