//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of PressureGradient.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class PressureGradientTestsBase
    {
        protected abstract double PascalPerMetersInOnePascalPerMeter { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double PascalPerMetersTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new PressureGradient((double)0.0, PressureGradientUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new PressureGradient();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(PressureGradientUnit.PascalPerMeter, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new PressureGradient(double.PositiveInfinity, PressureGradientUnit.PascalPerMeter));
            Assert.Throws<ArgumentException>(() => new PressureGradient(double.NegativeInfinity, PressureGradientUnit.PascalPerMeter));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new PressureGradient(double.NaN, PressureGradientUnit.PascalPerMeter));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new PressureGradient(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void PressureGradient_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new PressureGradient(1, PressureGradientUnit.PascalPerMeter);

            QuantityInfo<PressureGradientUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(PressureGradient.Zero, quantityInfo.Zero);
            Assert.Equal("PressureGradient", quantityInfo.Name);
            Assert.Equal(QuantityType.PressureGradient, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<PressureGradientUnit>().Except(new[] {PressureGradientUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void PascalPerMeterToPressureGradientUnits()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            AssertEx.EqualTolerance(PascalPerMetersInOnePascalPerMeter, pascalpermeter.PascalPerMeters, PascalPerMetersTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = PressureGradient.From(1, PressureGradientUnit.PascalPerMeter);
            AssertEx.EqualTolerance(1, quantity00.PascalPerMeters, PascalPerMetersTolerance);
            Assert.Equal(PressureGradientUnit.PascalPerMeter, quantity00.Unit);

        }

        [Fact]
        public void FromPascalPerMeters_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => PressureGradient.FromPascalPerMeters(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => PressureGradient.FromPascalPerMeters(double.NegativeInfinity));
        }

        [Fact]
        public void FromPascalPerMeters_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => PressureGradient.FromPascalPerMeters(double.NaN));
        }

        [Fact]
        public void As()
        {
            var pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            AssertEx.EqualTolerance(PascalPerMetersInOnePascalPerMeter, pascalpermeter.As(PressureGradientUnit.PascalPerMeter), PascalPerMetersTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var pascalpermeter = PressureGradient.FromPascalPerMeters(1);

            var pascalpermeterQuantity = pascalpermeter.ToUnit(PressureGradientUnit.PascalPerMeter);
            AssertEx.EqualTolerance(PascalPerMetersInOnePascalPerMeter, (double)pascalpermeterQuantity.Value, PascalPerMetersTolerance);
            Assert.Equal(PressureGradientUnit.PascalPerMeter, pascalpermeterQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            AssertEx.EqualTolerance(1, PressureGradient.FromPascalPerMeters(pascalpermeter.PascalPerMeters).PascalPerMeters, PascalPerMetersTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            PressureGradient v = PressureGradient.FromPascalPerMeters(1);
            AssertEx.EqualTolerance(-1, -v.PascalPerMeters, PascalPerMetersTolerance);
            AssertEx.EqualTolerance(2, (PressureGradient.FromPascalPerMeters(3)-v).PascalPerMeters, PascalPerMetersTolerance);
            AssertEx.EqualTolerance(2, (v + v).PascalPerMeters, PascalPerMetersTolerance);
            AssertEx.EqualTolerance(10, (v*10).PascalPerMeters, PascalPerMetersTolerance);
            AssertEx.EqualTolerance(10, (10*v).PascalPerMeters, PascalPerMetersTolerance);
            AssertEx.EqualTolerance(2, (PressureGradient.FromPascalPerMeters(10)/5).PascalPerMeters, PascalPerMetersTolerance);
            AssertEx.EqualTolerance(2, PressureGradient.FromPascalPerMeters(10)/PressureGradient.FromPascalPerMeters(5), PascalPerMetersTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            PressureGradient onePascalPerMeter = PressureGradient.FromPascalPerMeters(1);
            PressureGradient twoPascalPerMeters = PressureGradient.FromPascalPerMeters(2);

            Assert.True(onePascalPerMeter < twoPascalPerMeters);
            Assert.True(onePascalPerMeter <= twoPascalPerMeters);
            Assert.True(twoPascalPerMeters > onePascalPerMeter);
            Assert.True(twoPascalPerMeters >= onePascalPerMeter);

            Assert.False(onePascalPerMeter > twoPascalPerMeters);
            Assert.False(onePascalPerMeter >= twoPascalPerMeters);
            Assert.False(twoPascalPerMeters < onePascalPerMeter);
            Assert.False(twoPascalPerMeters <= onePascalPerMeter);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            Assert.Equal(0, pascalpermeter.CompareTo(pascalpermeter));
            Assert.True(pascalpermeter.CompareTo(PressureGradient.Zero) > 0);
            Assert.True(PressureGradient.Zero.CompareTo(pascalpermeter) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            Assert.Throws<ArgumentException>(() => pascalpermeter.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            Assert.Throws<ArgumentNullException>(() => pascalpermeter.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = PressureGradient.FromPascalPerMeters(1);
            var b = PressureGradient.FromPascalPerMeters(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = PressureGradient.FromPascalPerMeters(1);
            var b = PressureGradient.FromPascalPerMeters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = PressureGradient.FromPascalPerMeters(1);
            object b = PressureGradient.FromPascalPerMeters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = PressureGradient.FromPascalPerMeters(1);
            Assert.True(v.Equals(PressureGradient.FromPascalPerMeters(1), PascalPerMetersTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(PressureGradient.Zero, PascalPerMetersTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = PressureGradient.FromPascalPerMeters(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(PressureGradient.FromPascalPerMeters(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            Assert.False(pascalpermeter.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            PressureGradient pascalpermeter = PressureGradient.FromPascalPerMeters(1);
            Assert.False(pascalpermeter.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(PressureGradientUnit.Undefined, PressureGradient.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(PressureGradientUnit)).Cast<PressureGradientUnit>();
            foreach(var unit in units)
            {
                if(unit == PressureGradientUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(PressureGradient.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 Pa/m", new PressureGradient(1, PressureGradientUnit.PascalPerMeter).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 Pa/m", new PressureGradient(1, PressureGradientUnit.PascalPerMeter).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s1"));
                Assert.Equal("0.12 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s2"));
                Assert.Equal("0.123 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s3"));
                Assert.Equal("0.1235 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s1", culture));
            Assert.Equal("0.12 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s2", culture));
            Assert.Equal("0.123 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s3", culture));
            Assert.Equal("0.1235 Pa/m", new PressureGradient(0.123456, PressureGradientUnit.PascalPerMeter).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(PressureGradient)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(PressureGradientUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(QuantityType.PressureGradient, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(PressureGradient.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = PressureGradient.FromPascalPerMeters(1.0);
            Assert.Equal(new {PressureGradient.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = PressureGradient.FromPascalPerMeters(value);
            Assert.Equal(PressureGradient.FromPascalPerMeters(-value), -quantity);
        }

    }
}
