//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of RadiantIntensity.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class RadiantIntensityTestsBase
    {
        protected abstract double WattPerSteradiansInOneWattPerSteradian { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double WattPerSteradiansTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new RadiantIntensity((double)0.0, RadiantIntensityUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new RadiantIntensity();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(RadiantIntensityUnit.WattPerSteradian, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new RadiantIntensity(double.PositiveInfinity, RadiantIntensityUnit.WattPerSteradian));
            Assert.Throws<ArgumentException>(() => new RadiantIntensity(double.NegativeInfinity, RadiantIntensityUnit.WattPerSteradian));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new RadiantIntensity(double.NaN, RadiantIntensityUnit.WattPerSteradian));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new RadiantIntensity(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void RadiantIntensity_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new RadiantIntensity(1, RadiantIntensityUnit.WattPerSteradian);

            QuantityInfo<RadiantIntensityUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(RadiantIntensity.Zero, quantityInfo.Zero);
            Assert.Equal("RadiantIntensity", quantityInfo.Name);
            Assert.Equal(QuantityType.RadiantIntensity, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<RadiantIntensityUnit>().Except(new[] {RadiantIntensityUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void WattPerSteradianToRadiantIntensityUnits()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            AssertEx.EqualTolerance(WattPerSteradiansInOneWattPerSteradian, wattpersteradian.WattPerSteradians, WattPerSteradiansTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = RadiantIntensity.From(1, RadiantIntensityUnit.WattPerSteradian);
            AssertEx.EqualTolerance(1, quantity00.WattPerSteradians, WattPerSteradiansTolerance);
            Assert.Equal(RadiantIntensityUnit.WattPerSteradian, quantity00.Unit);

        }

        [Fact]
        public void FromWattPerSteradians_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => RadiantIntensity.FromWattPerSteradians(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => RadiantIntensity.FromWattPerSteradians(double.NegativeInfinity));
        }

        [Fact]
        public void FromWattPerSteradians_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => RadiantIntensity.FromWattPerSteradians(double.NaN));
        }

        [Fact]
        public void As()
        {
            var wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            AssertEx.EqualTolerance(WattPerSteradiansInOneWattPerSteradian, wattpersteradian.As(RadiantIntensityUnit.WattPerSteradian), WattPerSteradiansTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);

            var wattpersteradianQuantity = wattpersteradian.ToUnit(RadiantIntensityUnit.WattPerSteradian);
            AssertEx.EqualTolerance(WattPerSteradiansInOneWattPerSteradian, (double)wattpersteradianQuantity.Value, WattPerSteradiansTolerance);
            Assert.Equal(RadiantIntensityUnit.WattPerSteradian, wattpersteradianQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            AssertEx.EqualTolerance(1, RadiantIntensity.FromWattPerSteradians(wattpersteradian.WattPerSteradians).WattPerSteradians, WattPerSteradiansTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            RadiantIntensity v = RadiantIntensity.FromWattPerSteradians(1);
            AssertEx.EqualTolerance(-1, -v.WattPerSteradians, WattPerSteradiansTolerance);
            AssertEx.EqualTolerance(2, (RadiantIntensity.FromWattPerSteradians(3)-v).WattPerSteradians, WattPerSteradiansTolerance);
            AssertEx.EqualTolerance(2, (v + v).WattPerSteradians, WattPerSteradiansTolerance);
            AssertEx.EqualTolerance(10, (v*10).WattPerSteradians, WattPerSteradiansTolerance);
            AssertEx.EqualTolerance(10, (10*v).WattPerSteradians, WattPerSteradiansTolerance);
            AssertEx.EqualTolerance(2, (RadiantIntensity.FromWattPerSteradians(10)/5).WattPerSteradians, WattPerSteradiansTolerance);
            AssertEx.EqualTolerance(2, RadiantIntensity.FromWattPerSteradians(10)/RadiantIntensity.FromWattPerSteradians(5), WattPerSteradiansTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            RadiantIntensity oneWattPerSteradian = RadiantIntensity.FromWattPerSteradians(1);
            RadiantIntensity twoWattPerSteradians = RadiantIntensity.FromWattPerSteradians(2);

            Assert.True(oneWattPerSteradian < twoWattPerSteradians);
            Assert.True(oneWattPerSteradian <= twoWattPerSteradians);
            Assert.True(twoWattPerSteradians > oneWattPerSteradian);
            Assert.True(twoWattPerSteradians >= oneWattPerSteradian);

            Assert.False(oneWattPerSteradian > twoWattPerSteradians);
            Assert.False(oneWattPerSteradian >= twoWattPerSteradians);
            Assert.False(twoWattPerSteradians < oneWattPerSteradian);
            Assert.False(twoWattPerSteradians <= oneWattPerSteradian);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            Assert.Equal(0, wattpersteradian.CompareTo(wattpersteradian));
            Assert.True(wattpersteradian.CompareTo(RadiantIntensity.Zero) > 0);
            Assert.True(RadiantIntensity.Zero.CompareTo(wattpersteradian) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            Assert.Throws<ArgumentException>(() => wattpersteradian.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            Assert.Throws<ArgumentNullException>(() => wattpersteradian.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = RadiantIntensity.FromWattPerSteradians(1);
            var b = RadiantIntensity.FromWattPerSteradians(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = RadiantIntensity.FromWattPerSteradians(1);
            var b = RadiantIntensity.FromWattPerSteradians(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = RadiantIntensity.FromWattPerSteradians(1);
            object b = RadiantIntensity.FromWattPerSteradians(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = RadiantIntensity.FromWattPerSteradians(1);
            Assert.True(v.Equals(RadiantIntensity.FromWattPerSteradians(1), WattPerSteradiansTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(RadiantIntensity.Zero, WattPerSteradiansTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = RadiantIntensity.FromWattPerSteradians(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(RadiantIntensity.FromWattPerSteradians(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            Assert.False(wattpersteradian.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            RadiantIntensity wattpersteradian = RadiantIntensity.FromWattPerSteradians(1);
            Assert.False(wattpersteradian.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(RadiantIntensityUnit.Undefined, RadiantIntensity.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(RadiantIntensityUnit)).Cast<RadiantIntensityUnit>();
            foreach(var unit in units)
            {
                if(unit == RadiantIntensityUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(RadiantIntensity.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 W/sr", new RadiantIntensity(1, RadiantIntensityUnit.WattPerSteradian).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 W/sr", new RadiantIntensity(1, RadiantIntensityUnit.WattPerSteradian).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s1"));
                Assert.Equal("0.12 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s2"));
                Assert.Equal("0.123 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s3"));
                Assert.Equal("0.1235 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s1", culture));
            Assert.Equal("0.12 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s2", culture));
            Assert.Equal("0.123 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s3", culture));
            Assert.Equal("0.1235 W/sr", new RadiantIntensity(0.123456, RadiantIntensityUnit.WattPerSteradian).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(RadiantIntensity)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(RadiantIntensityUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(QuantityType.RadiantIntensity, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(RadiantIntensity.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(1.0);
            Assert.Equal(new {RadiantIntensity.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = RadiantIntensity.FromWattPerSteradians(value);
            Assert.Equal(RadiantIntensity.FromWattPerSteradians(-value), -quantity);
        }

    }
}
