//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of Radiance.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class RadianceTestsBase
    {
        protected abstract double WattPerSquareMeterSteradiansInOneWattPerSquareMeterSteradian { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double WattPerSquareMeterSteradiansTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Radiance((double)0.0, RadianceUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new Radiance();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(RadianceUnit.WattPerSquareMeterSteradian, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Radiance(double.PositiveInfinity, RadianceUnit.WattPerSquareMeterSteradian));
            Assert.Throws<ArgumentException>(() => new Radiance(double.NegativeInfinity, RadianceUnit.WattPerSquareMeterSteradian));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Radiance(double.NaN, RadianceUnit.WattPerSquareMeterSteradian));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new Radiance(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void Radiance_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new Radiance(1, RadianceUnit.WattPerSquareMeterSteradian);

            QuantityInfo<RadianceUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(Radiance.Zero, quantityInfo.Zero);
            Assert.Equal("Radiance", quantityInfo.Name);
            Assert.Equal(QuantityType.Radiance, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<RadianceUnit>().Except(new[] {RadianceUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void WattPerSquareMeterSteradianToRadianceUnits()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            AssertEx.EqualTolerance(WattPerSquareMeterSteradiansInOneWattPerSquareMeterSteradian, wattpersquaremetersteradian.WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = Radiance.From(1, RadianceUnit.WattPerSquareMeterSteradian);
            AssertEx.EqualTolerance(1, quantity00.WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            Assert.Equal(RadianceUnit.WattPerSquareMeterSteradian, quantity00.Unit);

        }

        [Fact]
        public void FromWattPerSquareMeterSteradians_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => Radiance.FromWattPerSquareMeterSteradians(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => Radiance.FromWattPerSquareMeterSteradians(double.NegativeInfinity));
        }

        [Fact]
        public void FromWattPerSquareMeterSteradians_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => Radiance.FromWattPerSquareMeterSteradians(double.NaN));
        }

        [Fact]
        public void As()
        {
            var wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            AssertEx.EqualTolerance(WattPerSquareMeterSteradiansInOneWattPerSquareMeterSteradian, wattpersquaremetersteradian.As(RadianceUnit.WattPerSquareMeterSteradian), WattPerSquareMeterSteradiansTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);

            var wattpersquaremetersteradianQuantity = wattpersquaremetersteradian.ToUnit(RadianceUnit.WattPerSquareMeterSteradian);
            AssertEx.EqualTolerance(WattPerSquareMeterSteradiansInOneWattPerSquareMeterSteradian, (double)wattpersquaremetersteradianQuantity.Value, WattPerSquareMeterSteradiansTolerance);
            Assert.Equal(RadianceUnit.WattPerSquareMeterSteradian, wattpersquaremetersteradianQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            AssertEx.EqualTolerance(1, Radiance.FromWattPerSquareMeterSteradians(wattpersquaremetersteradian.WattPerSquareMeterSteradians).WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            Radiance v = Radiance.FromWattPerSquareMeterSteradians(1);
            AssertEx.EqualTolerance(-1, -v.WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            AssertEx.EqualTolerance(2, (Radiance.FromWattPerSquareMeterSteradians(3)-v).WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            AssertEx.EqualTolerance(2, (v + v).WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            AssertEx.EqualTolerance(10, (v*10).WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            AssertEx.EqualTolerance(10, (10*v).WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            AssertEx.EqualTolerance(2, (Radiance.FromWattPerSquareMeterSteradians(10)/5).WattPerSquareMeterSteradians, WattPerSquareMeterSteradiansTolerance);
            AssertEx.EqualTolerance(2, Radiance.FromWattPerSquareMeterSteradians(10)/Radiance.FromWattPerSquareMeterSteradians(5), WattPerSquareMeterSteradiansTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            Radiance oneWattPerSquareMeterSteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            Radiance twoWattPerSquareMeterSteradians = Radiance.FromWattPerSquareMeterSteradians(2);

            Assert.True(oneWattPerSquareMeterSteradian < twoWattPerSquareMeterSteradians);
            Assert.True(oneWattPerSquareMeterSteradian <= twoWattPerSquareMeterSteradians);
            Assert.True(twoWattPerSquareMeterSteradians > oneWattPerSquareMeterSteradian);
            Assert.True(twoWattPerSquareMeterSteradians >= oneWattPerSquareMeterSteradian);

            Assert.False(oneWattPerSquareMeterSteradian > twoWattPerSquareMeterSteradians);
            Assert.False(oneWattPerSquareMeterSteradian >= twoWattPerSquareMeterSteradians);
            Assert.False(twoWattPerSquareMeterSteradians < oneWattPerSquareMeterSteradian);
            Assert.False(twoWattPerSquareMeterSteradians <= oneWattPerSquareMeterSteradian);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.Equal(0, wattpersquaremetersteradian.CompareTo(wattpersquaremetersteradian));
            Assert.True(wattpersquaremetersteradian.CompareTo(Radiance.Zero) > 0);
            Assert.True(Radiance.Zero.CompareTo(wattpersquaremetersteradian) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.Throws<ArgumentException>(() => wattpersquaremetersteradian.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.Throws<ArgumentNullException>(() => wattpersquaremetersteradian.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = Radiance.FromWattPerSquareMeterSteradians(1);
            var b = Radiance.FromWattPerSquareMeterSteradians(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = Radiance.FromWattPerSquareMeterSteradians(1);
            var b = Radiance.FromWattPerSquareMeterSteradians(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = Radiance.FromWattPerSquareMeterSteradians(1);
            object b = Radiance.FromWattPerSquareMeterSteradians(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.True(v.Equals(Radiance.FromWattPerSquareMeterSteradians(1), WattPerSquareMeterSteradiansTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(Radiance.Zero, WattPerSquareMeterSteradiansTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(Radiance.FromWattPerSquareMeterSteradians(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.False(wattpersquaremetersteradian.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            Radiance wattpersquaremetersteradian = Radiance.FromWattPerSquareMeterSteradians(1);
            Assert.False(wattpersquaremetersteradian.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(RadianceUnit.Undefined, Radiance.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(RadianceUnit)).Cast<RadianceUnit>();
            foreach(var unit in units)
            {
                if(unit == RadianceUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(Radiance.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 W/(m².sr)", new Radiance(1, RadianceUnit.WattPerSquareMeterSteradian).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 W/(m².sr)", new Radiance(1, RadianceUnit.WattPerSquareMeterSteradian).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s1"));
                Assert.Equal("0.12 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s2"));
                Assert.Equal("0.123 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s3"));
                Assert.Equal("0.1235 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s1", culture));
            Assert.Equal("0.12 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s2", culture));
            Assert.Equal("0.123 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s3", culture));
            Assert.Equal("0.1235 W/(m².sr)", new Radiance(0.123456, RadianceUnit.WattPerSquareMeterSteradian).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(Radiance)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(RadianceUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(QuantityType.Radiance, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(Radiance.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(1.0);
            Assert.Equal(new {Radiance.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = Radiance.FromWattPerSquareMeterSteradians(value);
            Assert.Equal(Radiance.FromWattPerSquareMeterSteradians(-value), -quantity);
        }

    }
}
