//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of SpaceVelocity.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class SpaceVelocityTestsBase
    {
        protected abstract double LiterPerSecondCubicMetersInOneLiterPerSecondCubicMeter { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double LiterPerSecondCubicMetersTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new SpaceVelocity((double)0.0, SpaceVelocityUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new SpaceVelocity();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(SpaceVelocityUnit.LiterPerSecondCubicMeter, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new SpaceVelocity(double.PositiveInfinity, SpaceVelocityUnit.LiterPerSecondCubicMeter));
            Assert.Throws<ArgumentException>(() => new SpaceVelocity(double.NegativeInfinity, SpaceVelocityUnit.LiterPerSecondCubicMeter));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new SpaceVelocity(double.NaN, SpaceVelocityUnit.LiterPerSecondCubicMeter));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new SpaceVelocity(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void SpaceVelocity_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new SpaceVelocity(1, SpaceVelocityUnit.LiterPerSecondCubicMeter);

            QuantityInfo<SpaceVelocityUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(SpaceVelocity.Zero, quantityInfo.Zero);
            Assert.Equal("SpaceVelocity", quantityInfo.Name);
            Assert.Equal(QuantityType.SpaceVelocity, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<SpaceVelocityUnit>().Except(new[] {SpaceVelocityUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void LiterPerSecondCubicMeterToSpaceVelocityUnits()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            AssertEx.EqualTolerance(LiterPerSecondCubicMetersInOneLiterPerSecondCubicMeter, literpersecondcubicmeter.LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = SpaceVelocity.From(1, SpaceVelocityUnit.LiterPerSecondCubicMeter);
            AssertEx.EqualTolerance(1, quantity00.LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            Assert.Equal(SpaceVelocityUnit.LiterPerSecondCubicMeter, quantity00.Unit);

        }

        [Fact]
        public void FromLiterPerSecondCubicMeters_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => SpaceVelocity.FromLiterPerSecondCubicMeters(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => SpaceVelocity.FromLiterPerSecondCubicMeters(double.NegativeInfinity));
        }

        [Fact]
        public void FromLiterPerSecondCubicMeters_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => SpaceVelocity.FromLiterPerSecondCubicMeters(double.NaN));
        }

        [Fact]
        public void As()
        {
            var literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            AssertEx.EqualTolerance(LiterPerSecondCubicMetersInOneLiterPerSecondCubicMeter, literpersecondcubicmeter.As(SpaceVelocityUnit.LiterPerSecondCubicMeter), LiterPerSecondCubicMetersTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);

            var literpersecondcubicmeterQuantity = literpersecondcubicmeter.ToUnit(SpaceVelocityUnit.LiterPerSecondCubicMeter);
            AssertEx.EqualTolerance(LiterPerSecondCubicMetersInOneLiterPerSecondCubicMeter, (double)literpersecondcubicmeterQuantity.Value, LiterPerSecondCubicMetersTolerance);
            Assert.Equal(SpaceVelocityUnit.LiterPerSecondCubicMeter, literpersecondcubicmeterQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            AssertEx.EqualTolerance(1, SpaceVelocity.FromLiterPerSecondCubicMeters(literpersecondcubicmeter.LiterPerSecondCubicMeters).LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            SpaceVelocity v = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            AssertEx.EqualTolerance(-1, -v.LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            AssertEx.EqualTolerance(2, (SpaceVelocity.FromLiterPerSecondCubicMeters(3)-v).LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            AssertEx.EqualTolerance(2, (v + v).LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            AssertEx.EqualTolerance(10, (v*10).LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            AssertEx.EqualTolerance(10, (10*v).LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            AssertEx.EqualTolerance(2, (SpaceVelocity.FromLiterPerSecondCubicMeters(10)/5).LiterPerSecondCubicMeters, LiterPerSecondCubicMetersTolerance);
            AssertEx.EqualTolerance(2, SpaceVelocity.FromLiterPerSecondCubicMeters(10)/SpaceVelocity.FromLiterPerSecondCubicMeters(5), LiterPerSecondCubicMetersTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            SpaceVelocity oneLiterPerSecondCubicMeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            SpaceVelocity twoLiterPerSecondCubicMeters = SpaceVelocity.FromLiterPerSecondCubicMeters(2);

            Assert.True(oneLiterPerSecondCubicMeter < twoLiterPerSecondCubicMeters);
            Assert.True(oneLiterPerSecondCubicMeter <= twoLiterPerSecondCubicMeters);
            Assert.True(twoLiterPerSecondCubicMeters > oneLiterPerSecondCubicMeter);
            Assert.True(twoLiterPerSecondCubicMeters >= oneLiterPerSecondCubicMeter);

            Assert.False(oneLiterPerSecondCubicMeter > twoLiterPerSecondCubicMeters);
            Assert.False(oneLiterPerSecondCubicMeter >= twoLiterPerSecondCubicMeters);
            Assert.False(twoLiterPerSecondCubicMeters < oneLiterPerSecondCubicMeter);
            Assert.False(twoLiterPerSecondCubicMeters <= oneLiterPerSecondCubicMeter);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.Equal(0, literpersecondcubicmeter.CompareTo(literpersecondcubicmeter));
            Assert.True(literpersecondcubicmeter.CompareTo(SpaceVelocity.Zero) > 0);
            Assert.True(SpaceVelocity.Zero.CompareTo(literpersecondcubicmeter) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.Throws<ArgumentException>(() => literpersecondcubicmeter.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.Throws<ArgumentNullException>(() => literpersecondcubicmeter.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            var b = SpaceVelocity.FromLiterPerSecondCubicMeters(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            var b = SpaceVelocity.FromLiterPerSecondCubicMeters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            object b = SpaceVelocity.FromLiterPerSecondCubicMeters(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.True(v.Equals(SpaceVelocity.FromLiterPerSecondCubicMeters(1), LiterPerSecondCubicMetersTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(SpaceVelocity.Zero, LiterPerSecondCubicMetersTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(SpaceVelocity.FromLiterPerSecondCubicMeters(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.False(literpersecondcubicmeter.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            SpaceVelocity literpersecondcubicmeter = SpaceVelocity.FromLiterPerSecondCubicMeters(1);
            Assert.False(literpersecondcubicmeter.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(SpaceVelocityUnit.Undefined, SpaceVelocity.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(SpaceVelocityUnit)).Cast<SpaceVelocityUnit>();
            foreach(var unit in units)
            {
                if(unit == SpaceVelocityUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(SpaceVelocity.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 L/(s·m³)", new SpaceVelocity(1, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 L/(s·m³)", new SpaceVelocity(1, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s1"));
                Assert.Equal("0.12 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s2"));
                Assert.Equal("0.123 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s3"));
                Assert.Equal("0.1235 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s1", culture));
            Assert.Equal("0.12 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s2", culture));
            Assert.Equal("0.123 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s3", culture));
            Assert.Equal("0.1235 L/(s·m³)", new SpaceVelocity(0.123456, SpaceVelocityUnit.LiterPerSecondCubicMeter).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(SpaceVelocity)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(SpaceVelocityUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(QuantityType.SpaceVelocity, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(SpaceVelocity.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(1.0);
            Assert.Equal(new {SpaceVelocity.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = SpaceVelocity.FromLiterPerSecondCubicMeters(value);
            Assert.Equal(SpaceVelocity.FromLiterPerSecondCubicMeters(-value), -quantity);
        }

    }
}
