//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of SpecificLength.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class SpecificLengthTestsBase
    {
        protected abstract double MeterPerGramsInOneMeterPerGram { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double MeterPerGramsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new SpecificLength((double)0.0, SpecificLengthUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new SpecificLength();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(SpecificLengthUnit.MeterPerGram, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new SpecificLength(double.PositiveInfinity, SpecificLengthUnit.MeterPerGram));
            Assert.Throws<ArgumentException>(() => new SpecificLength(double.NegativeInfinity, SpecificLengthUnit.MeterPerGram));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new SpecificLength(double.NaN, SpecificLengthUnit.MeterPerGram));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new SpecificLength(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void SpecificLength_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new SpecificLength(1, SpecificLengthUnit.MeterPerGram);

            QuantityInfo<SpecificLengthUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(SpecificLength.Zero, quantityInfo.Zero);
            Assert.Equal("SpecificLength", quantityInfo.Name);
            Assert.Equal(QuantityType.SpecificLength, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<SpecificLengthUnit>().Except(new[] {SpecificLengthUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void MeterPerGramToSpecificLengthUnits()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            AssertEx.EqualTolerance(MeterPerGramsInOneMeterPerGram, meterpergram.MeterPerGrams, MeterPerGramsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = SpecificLength.From(1, SpecificLengthUnit.MeterPerGram);
            AssertEx.EqualTolerance(1, quantity00.MeterPerGrams, MeterPerGramsTolerance);
            Assert.Equal(SpecificLengthUnit.MeterPerGram, quantity00.Unit);

        }

        [Fact]
        public void FromMeterPerGrams_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => SpecificLength.FromMeterPerGrams(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => SpecificLength.FromMeterPerGrams(double.NegativeInfinity));
        }

        [Fact]
        public void FromMeterPerGrams_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => SpecificLength.FromMeterPerGrams(double.NaN));
        }

        [Fact]
        public void As()
        {
            var meterpergram = SpecificLength.FromMeterPerGrams(1);
            AssertEx.EqualTolerance(MeterPerGramsInOneMeterPerGram, meterpergram.As(SpecificLengthUnit.MeterPerGram), MeterPerGramsTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var meterpergram = SpecificLength.FromMeterPerGrams(1);

            var meterpergramQuantity = meterpergram.ToUnit(SpecificLengthUnit.MeterPerGram);
            AssertEx.EqualTolerance(MeterPerGramsInOneMeterPerGram, (double)meterpergramQuantity.Value, MeterPerGramsTolerance);
            Assert.Equal(SpecificLengthUnit.MeterPerGram, meterpergramQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            AssertEx.EqualTolerance(1, SpecificLength.FromMeterPerGrams(meterpergram.MeterPerGrams).MeterPerGrams, MeterPerGramsTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            SpecificLength v = SpecificLength.FromMeterPerGrams(1);
            AssertEx.EqualTolerance(-1, -v.MeterPerGrams, MeterPerGramsTolerance);
            AssertEx.EqualTolerance(2, (SpecificLength.FromMeterPerGrams(3)-v).MeterPerGrams, MeterPerGramsTolerance);
            AssertEx.EqualTolerance(2, (v + v).MeterPerGrams, MeterPerGramsTolerance);
            AssertEx.EqualTolerance(10, (v*10).MeterPerGrams, MeterPerGramsTolerance);
            AssertEx.EqualTolerance(10, (10*v).MeterPerGrams, MeterPerGramsTolerance);
            AssertEx.EqualTolerance(2, (SpecificLength.FromMeterPerGrams(10)/5).MeterPerGrams, MeterPerGramsTolerance);
            AssertEx.EqualTolerance(2, SpecificLength.FromMeterPerGrams(10)/SpecificLength.FromMeterPerGrams(5), MeterPerGramsTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            SpecificLength oneMeterPerGram = SpecificLength.FromMeterPerGrams(1);
            SpecificLength twoMeterPerGrams = SpecificLength.FromMeterPerGrams(2);

            Assert.True(oneMeterPerGram < twoMeterPerGrams);
            Assert.True(oneMeterPerGram <= twoMeterPerGrams);
            Assert.True(twoMeterPerGrams > oneMeterPerGram);
            Assert.True(twoMeterPerGrams >= oneMeterPerGram);

            Assert.False(oneMeterPerGram > twoMeterPerGrams);
            Assert.False(oneMeterPerGram >= twoMeterPerGrams);
            Assert.False(twoMeterPerGrams < oneMeterPerGram);
            Assert.False(twoMeterPerGrams <= oneMeterPerGram);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            Assert.Equal(0, meterpergram.CompareTo(meterpergram));
            Assert.True(meterpergram.CompareTo(SpecificLength.Zero) > 0);
            Assert.True(SpecificLength.Zero.CompareTo(meterpergram) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            Assert.Throws<ArgumentException>(() => meterpergram.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            Assert.Throws<ArgumentNullException>(() => meterpergram.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = SpecificLength.FromMeterPerGrams(1);
            var b = SpecificLength.FromMeterPerGrams(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = SpecificLength.FromMeterPerGrams(1);
            var b = SpecificLength.FromMeterPerGrams(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = SpecificLength.FromMeterPerGrams(1);
            object b = SpecificLength.FromMeterPerGrams(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = SpecificLength.FromMeterPerGrams(1);
            Assert.True(v.Equals(SpecificLength.FromMeterPerGrams(1), MeterPerGramsTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(SpecificLength.Zero, MeterPerGramsTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = SpecificLength.FromMeterPerGrams(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(SpecificLength.FromMeterPerGrams(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            Assert.False(meterpergram.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            SpecificLength meterpergram = SpecificLength.FromMeterPerGrams(1);
            Assert.False(meterpergram.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(SpecificLengthUnit.Undefined, SpecificLength.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(SpecificLengthUnit)).Cast<SpecificLengthUnit>();
            foreach(var unit in units)
            {
                if(unit == SpecificLengthUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(SpecificLength.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 m/g", new SpecificLength(1, SpecificLengthUnit.MeterPerGram).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 m/g", new SpecificLength(1, SpecificLengthUnit.MeterPerGram).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s1"));
                Assert.Equal("0.12 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s2"));
                Assert.Equal("0.123 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s3"));
                Assert.Equal("0.1235 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s1", culture));
            Assert.Equal("0.12 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s2", culture));
            Assert.Equal("0.123 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s3", culture));
            Assert.Equal("0.1235 m/g", new SpecificLength(0.123456, SpecificLengthUnit.MeterPerGram).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(SpecificLength)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(SpecificLengthUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(QuantityType.SpecificLength, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(SpecificLength.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = SpecificLength.FromMeterPerGrams(1.0);
            Assert.Equal(new {SpecificLength.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = SpecificLength.FromMeterPerGrams(value);
            Assert.Equal(SpecificLength.FromMeterPerGrams(-value), -quantity);
        }

    }
}
