//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of ThermalConductance.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class ThermalConductanceTestsBase
    {
        protected abstract double WattPerKelvinsInOneWattPerKelvin { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double WattPerKelvinsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new ThermalConductance((double)0.0, ThermalConductanceUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new ThermalConductance();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(ThermalConductanceUnit.WattPerKelvin, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new ThermalConductance(double.PositiveInfinity, ThermalConductanceUnit.WattPerKelvin));
            Assert.Throws<ArgumentException>(() => new ThermalConductance(double.NegativeInfinity, ThermalConductanceUnit.WattPerKelvin));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new ThermalConductance(double.NaN, ThermalConductanceUnit.WattPerKelvin));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new ThermalConductance(value: 1.0, unitSystem: null));
        }

        [Fact]
        public void ThermalConductance_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new ThermalConductance(1, ThermalConductanceUnit.WattPerKelvin);

            QuantityInfo<ThermalConductanceUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(ThermalConductance.Zero, quantityInfo.Zero);
            Assert.Equal("ThermalConductance", quantityInfo.Name);
            Assert.Equal(QuantityType.ThermalConductance, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<ThermalConductanceUnit>().Except(new[] {ThermalConductanceUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
#pragma warning disable 618
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
#pragma warning restore 618
        }

        [Fact]
        public void WattPerKelvinToThermalConductanceUnits()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            AssertEx.EqualTolerance(WattPerKelvinsInOneWattPerKelvin, wattperkelvin.WattPerKelvins, WattPerKelvinsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = ThermalConductance.From(1, ThermalConductanceUnit.WattPerKelvin);
            AssertEx.EqualTolerance(1, quantity00.WattPerKelvins, WattPerKelvinsTolerance);
            Assert.Equal(ThermalConductanceUnit.WattPerKelvin, quantity00.Unit);

        }

        [Fact]
        public void FromWattPerKelvins_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => ThermalConductance.FromWattPerKelvins(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => ThermalConductance.FromWattPerKelvins(double.NegativeInfinity));
        }

        [Fact]
        public void FromWattPerKelvins_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => ThermalConductance.FromWattPerKelvins(double.NaN));
        }

        [Fact]
        public void As()
        {
            var wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            AssertEx.EqualTolerance(WattPerKelvinsInOneWattPerKelvin, wattperkelvin.As(ThermalConductanceUnit.WattPerKelvin), WattPerKelvinsTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var wattperkelvin = ThermalConductance.FromWattPerKelvins(1);

            var wattperkelvinQuantity = wattperkelvin.ToUnit(ThermalConductanceUnit.WattPerKelvin);
            AssertEx.EqualTolerance(WattPerKelvinsInOneWattPerKelvin, (double)wattperkelvinQuantity.Value, WattPerKelvinsTolerance);
            Assert.Equal(ThermalConductanceUnit.WattPerKelvin, wattperkelvinQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            AssertEx.EqualTolerance(1, ThermalConductance.FromWattPerKelvins(wattperkelvin.WattPerKelvins).WattPerKelvins, WattPerKelvinsTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            ThermalConductance v = ThermalConductance.FromWattPerKelvins(1);
            AssertEx.EqualTolerance(-1, -v.WattPerKelvins, WattPerKelvinsTolerance);
            AssertEx.EqualTolerance(2, (ThermalConductance.FromWattPerKelvins(3)-v).WattPerKelvins, WattPerKelvinsTolerance);
            AssertEx.EqualTolerance(2, (v + v).WattPerKelvins, WattPerKelvinsTolerance);
            AssertEx.EqualTolerance(10, (v*10).WattPerKelvins, WattPerKelvinsTolerance);
            AssertEx.EqualTolerance(10, (10*v).WattPerKelvins, WattPerKelvinsTolerance);
            AssertEx.EqualTolerance(2, (ThermalConductance.FromWattPerKelvins(10)/5).WattPerKelvins, WattPerKelvinsTolerance);
            AssertEx.EqualTolerance(2, ThermalConductance.FromWattPerKelvins(10)/ThermalConductance.FromWattPerKelvins(5), WattPerKelvinsTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            ThermalConductance oneWattPerKelvin = ThermalConductance.FromWattPerKelvins(1);
            ThermalConductance twoWattPerKelvins = ThermalConductance.FromWattPerKelvins(2);

            Assert.True(oneWattPerKelvin < twoWattPerKelvins);
            Assert.True(oneWattPerKelvin <= twoWattPerKelvins);
            Assert.True(twoWattPerKelvins > oneWattPerKelvin);
            Assert.True(twoWattPerKelvins >= oneWattPerKelvin);

            Assert.False(oneWattPerKelvin > twoWattPerKelvins);
            Assert.False(oneWattPerKelvin >= twoWattPerKelvins);
            Assert.False(twoWattPerKelvins < oneWattPerKelvin);
            Assert.False(twoWattPerKelvins <= oneWattPerKelvin);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            Assert.Equal(0, wattperkelvin.CompareTo(wattperkelvin));
            Assert.True(wattperkelvin.CompareTo(ThermalConductance.Zero) > 0);
            Assert.True(ThermalConductance.Zero.CompareTo(wattperkelvin) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            Assert.Throws<ArgumentException>(() => wattperkelvin.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            Assert.Throws<ArgumentNullException>(() => wattperkelvin.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = ThermalConductance.FromWattPerKelvins(1);
            var b = ThermalConductance.FromWattPerKelvins(2);

 // ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = ThermalConductance.FromWattPerKelvins(1);
            var b = ThermalConductance.FromWattPerKelvins(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = ThermalConductance.FromWattPerKelvins(1);
            object b = ThermalConductance.FromWattPerKelvins(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = ThermalConductance.FromWattPerKelvins(1);
            Assert.True(v.Equals(ThermalConductance.FromWattPerKelvins(1), WattPerKelvinsTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(ThermalConductance.Zero, WattPerKelvinsTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = ThermalConductance.FromWattPerKelvins(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(ThermalConductance.FromWattPerKelvins(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            Assert.False(wattperkelvin.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattPerKelvins(1);
            Assert.False(wattperkelvin.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(ThermalConductanceUnit.Undefined, ThermalConductance.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(ThermalConductanceUnit)).Cast<ThermalConductanceUnit>();
            foreach(var unit in units)
            {
                if(unit == ThermalConductanceUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(ThermalConductance.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 W/K", new ThermalConductance(1, ThermalConductanceUnit.WattPerKelvin).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 W/K", new ThermalConductance(1, ThermalConductanceUnit.WattPerKelvin).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s1"));
                Assert.Equal("0.12 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s2"));
                Assert.Equal("0.123 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s3"));
                Assert.Equal("0.1235 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s1", culture));
            Assert.Equal("0.12 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s2", culture));
            Assert.Equal("0.123 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s3", culture));
            Assert.Equal("0.1235 W/K", new ThermalConductance(0.123456, ThermalConductanceUnit.WattPerKelvin).ToString("s4", culture));
        }

        #pragma warning disable 612, 618

        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }

        #pragma warning restore 612, 618

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(ThermalConductance)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(ThermalConductanceUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(QuantityType.ThermalConductance, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(ThermalConductance.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = ThermalConductance.FromWattPerKelvins(1.0);
            Assert.Equal(new {ThermalConductance.QuantityType, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = ThermalConductance.FromWattPerKelvins(value);
            Assert.Equal(ThermalConductance.FromWattPerKelvins(-value), -quantity);
        }

    }
}
